# Generated by Django 4.1.5 on 2023-01-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chatting',
            new_name='Chat',
        ),
    ]
