# Generated by Django 4.1.5 on 2023-01-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0002_rename_chatting_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='output',
        ),
        migrations.AlterField(
            model_name='chat',
            name='input',
            field=models.CharField(max_length=100),
        ),
    ]
