# Generated by Django 4.1.5 on 2023-01-31 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0003_remove_chat_output_alter_chat_input'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
